name       : qt5-connectivity
version    : 5.14.2
release    : 19
source     :
    - https://download.qt.io/official_releases/qt/5.14/5.14.2/submodules/qtconnectivity-everywhere-src-5.14.2.tar.xz : abe67b3e3a775e2a2e27c62a5391f37007ffbe72bce58b96116995616cfcbc28
homepage   : https://www.qt.io
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Connectivity components
description: |
    Qt5 Connectivity Components
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtconnectivity.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
