name       : qt5-connectivity
version    : 5.15.1
release    : 20
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtconnectivity-everywhere-src-5.15.1.tar.xz : 53c30039d4f2301a1a66c646690436e1f8cce0a3fd212ca0783f346a115d8016
homepage   : https://www.qt.io
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Connectivity components
description: |
    Qt5 Connectivity Components
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtconnectivity.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
