name       : qt5-connectivity
version    : 5.12.3
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtconnectivity-everywhere-src-5.12.3.tar.xz : 01518cee71a8d53b9c2387f8c7facbcc2c4d63ab3b79462edfa06ba3bfeae661
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Connectivity components
description: |
    Qt5 Connectivity Components
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtconnectivity.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
