name       : qt5-connectivity
version    : 5.11.2
release    : 11
source     :
    - https://download.qt.io/official_releases/qt/5.11/5.11.2/submodules/qtconnectivity-everywhere-src-5.11.2.tar.xz : 58901bbd14d3bc472f27fe305fd8dc33cffbd10da83616e9691c04c3290d42c5
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Connectivity components
description: |
    Qt5 Connectivity Components
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtconnectivity.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
