name       : qt5-connectivity
version    : 5.11.0
release    : 9
source     :
    - http://qt.mirror.constant.com/official_releases/qt/5.11/5.11.0/submodules/qtconnectivity-everywhere-src-5.11.0.tar.xz : cd2e53b1a7bee098b651cbedcecf0717036ae4bec5de0daf3a0038a50b2e1873
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Connectivity components
description: |
    Qt5 Connectivity Components
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtconnectivity.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
